crystals:
  00000C0E:
    color: blue
    school: conjuration
    name: Kyber of Calling
  00000C04:
    color: green
    school: transmutation
    name: Kyber of Shaping
  00000C09:
    color: red
    school: evocation
    name: Kyber of the Striking Hand
  11000C03:
    color: yellow
    school: divination
    name: Kyber of the Seeker's Eye
  11000C00:
    color: white
    school: abjuration
    name: Kyber of Warding
  00000C07:
    color: pink
    school: enchantment
    name: Kyber of the Whispered Word
  00000C0A:
    color: orange
    school: illusion
    name: Kyber of the Painted Veil
  11000C33:
    color: black
    school: necromancy
    name: Kyber of the Final Door
